# Generated by Django 5.2.12 on 2026-03-22 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название котировки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Котировка',
                'verbose_name_plural': 'Котировки',
            },
        ),
        migrations.CreateModel(
            name='RealTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Объём')),
                ('asset', models.CharField(max_length=50, verbose_name='Актив')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Цена')),
                ('trade_type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=4, verbose_name='Тип сделки')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quote', verbose_name='Котировка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реальная сделка',
                'verbose_name_plural': 'Реальные сделки',
            },
        ),
        migrations.CreateModel(
            name='TrainingTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Объём')),
                ('asset', models.CharField(max_length=50, verbose_name='Актив')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Цена')),
                ('trade_type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=4, verbose_name='Тип сделки')),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quote', verbose_name='Котировка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тренировочная сделка',
                'verbose_name_plural': 'Тренировочные сделки',
            },
        ),
    ]
