# Generated by Django 6.0.3 on 2026-04-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='current_price',
            field=models.DecimalField(decimal_places=4, default=100.0, max_digits=12, verbose_name='Текущая цена'),
        ),
    ]
