# Generated by Django 6.0.3 on 2026-04-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления'),
        ),
    ]
