# Generated by Django 6.0.4 on 2026-04-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtrade',
            name='asset',
        ),
    ]
