# Generated by Django 6.0.4 on 2026-04-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_remove_trainingtrade_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={},
        ),
        migrations.AddField(
            model_name='quote',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Цена закрытия предыдущего дня'),
        ),
    ]
